# Generated by Django 3.2.5 on 2021-07-23 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf', '0002_alter_sede_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sede',
            options={},
        ),
    ]
