# Generated by Django 3.2.5 on 2021-08-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf', '0003_alter_sede_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacion',
            options={'permissions': [('view_consulta', 'Ver consultas'), ('add_consulta', 'Agregar consultas'), ('change_consulta', 'Editar consultas'), ('delete_consulta', 'Eliminar consultas')]},
        ),
    ]
