# Generated by Django 3.2.5 on 2021-08-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cetaf', '0004_alter_asignacion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activo',
            name='vida_util',
            field=models.FloatField(default=0),
        ),
    ]
